title: "@tyleretters — repositories"
baseurl: /
url: https://tyleretters.github.io/
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
include: ['_pages']
collections_dir: collections
collections:
  - repositories